stable_horde.py

fix: read source image from request

---

.gitignore
stable_horde.py

feat: get model name from horde database

---

stable_horde.py

This is part of #25 that fixes the submitting bug and add save images features.
It is better to cherry-pick the bug-fixes to the master branch to fix the emergence submitting bug immediately.
Co-authored-by: John Warnes <john@warnes.email>

fix: 400 error on submit generation

---

LICENSE

As Stable Horde WebUI uses [AGPL](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/d97f467c0d27695d23edad5e4f8898a57e0ccb00), we might need to use it as well.
close #18

chore: add AGPL license

---

readme.md

docs: update readme for clarify the worker bridge

---

stable_horde.py

feat: add bridge agent to api payload

---

scripts/script.py

with `gradio.utils.synchronize_async` api
This API is much simple than the request method.

refactor: start running bridge simplier

---

stable_horde.py

fix: add DPM fast Karras sampler

---

scripts/script.py
stable_horde.py

Enjoyed you extension! Thanks! It's a fun way to try out stable horde. I thought I would also share. 
I fixed a bug in the branch get it to work, and added a save feature to see what people have been generating when I am away.
**Bug**
Seed was being send as a string when stable horde wants a int. returned at 400 error.
**New feature "Save Images"**
- Option in horde config, default False
- Will save pnginfo if selected in main config
- Saves to horde directory
**Note**
If you don't go into the settings and enable all the Real-ESRGAN models under "Upscaling" you will get errors when the horde  uses them.
I hope it's a welcome pull request, but If this is unwanted go ahead and close the request.

feat: Save Images

---

.flake8
.github/workflows/lint.yml
install.py
requirements.txt
scripts/script.py
stable_horde.py

Also cleared some redundant code that was mistakenly merged before.

chore: lint existing code

---

stable_horde.py

- Getting 500 Server Error on submit, retry uploads the image fine
- Multiple delimiter in one prompt, chosed the last one and continue (should not happen)

500 server error, multiple delimiter 

---

stable_horde.py

add bridge agent information corresponding for the capabilities that this agent could do.
also we open a pull request on Stable Horde side: https://github.com/db0/AI-Horde/pull/146

refactor: update bridge agent version

---

readme.md

chore: add compatibilities in readme

---

stable_horde/horde.py

also add retry attemps, maybe we should extract it outside
fix #56

fix: get supported model on boot

---

stable_horde/horde.py

fix: ImportError when using newer webui version

---

.github/pull_request_template.md

chore: adjust pull request template sections

---

stable_horde/job.py

extract img2img source image from request itself not the payload, fix #65

fix: img2img ignored source images, fix #65

---

stable_horde/horde.py
stable_horde/job.py

Add state report for current job, such as `censored` or `faulted`.
Close #64

feat: add state report for current job

---

readme.md
stable_horde/horde.py
stable_horde/job.py

feat: add tiling feature support

---

readme.md

docs: update readme for features

---

stable_horde/job.py

feat: support r2 source feature

---

stable_horde/horde.py
stable_horde/job.py

feat: add clip skip feature

---

stable_horde/horde.py

Fixed:
[Sygil-Dev no longer the source for nataili](https://github.com/sdwebui-w-horde/sd-webui-stable-horde-worker/issues/74)

New origin for nataili

---

readme.md
scripts/script.py
stable_horde/config.py
stable_horde/horde.py

Select a set of models to share.
Implementing feature request: https://github.com/sdwebui-w-horde/sd-webui-stable-horde-worker/issues/3
- saves the currently selected models in a config with
their corresponding name.
- added a multi select dropdown to choose from local models. When selecting, hash gets compared to
remote hash.
- added override model checkpoint to parameters in order to swap model on the fly
- better state status by adding model and sampler of request
- targeted [Sygil-Dev no longer the source for nataili](https://github.com/sdwebui-w-horde/sd-webui-stable-horde-worker/issues/74) as well. Was only one line of code.
I implemented [Sygil-Dev no longer the source for nataili](https://github.com/sdwebui-w-horde/sd-webui-stable-horde-worker/issues/74) as well.

feat: add model switching (#75), close #3

---

stable_horde/horde.py

- added model hash search from checkpoints
- info text parsing model name and hash thanks to @VanishX for the code snippet
- (remark: used flake and black locally, hopefully this time it works)
closes #79

79 bug save images saved wrong model name

---

scripts/script.py

fix: save images button not working

---

stable_horde/horde.py

The current URL returns an empty JSON file, `{}`
This URL is from the official client. It appears to contain the content we're after, and it worked fine in testing.

Update supported models URL

---

stable_horde/horde.py

removed dead code

---

stable_horde/horde.py

fix: model hash from remote can be upper cases

---

stable_horde/horde.py

I added three more samplers to horde.py.
This pull request closes issues #117, #118 and #119.

Added three more samplers

---

scripts/script.py

These are the warnings, they occur on start:
/home/user/stable-diffusion-webui/extensions/sd-webui-stable-horde-worker/scripts/script.py:104: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
with gr.Row().style(equal_height=False):
/home/user/stable-diffusion-webui/extensions/sd-webui-stable-horde-worker/scripts/script.py:236: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
).style(grid=4)
/home/user/stable-diffusion-webui/extensions/sd-webui-stable-horde-worker/scripts/script.py:236: GradioDeprecationWarning: The 'grid' parameter will be deprecated. Please use 'columns' in the constructor instead.
).style(grid=4)

Fixed gradio warnings

---

scripts/script.py
stable_horde/horde.py

fix: syntax error from #121
